name: Rituals + Retreats
favicon: null
layout_spectrum: 0.178728390019387
typography_spectrum: 0.9939115897286683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5202840843703598
  lightness: 0.3340295413509011
  saturation: 0.5992010929621756
  rhythmicContrast: 0.2269998707342893
purpose: []
